name: WPENGINE static build and rsync deploy
on:
  push:
    branches:
      - master
      - future-staging-branch-name
jobs:
  Mill3-Deploy-Actions:
    runs-on: ubuntu-latest
    env:
      THEME_PATH: "wp-content/themes/mill3-wp-theme-boilerplate/"
      WPENGINE_ENV_NAME: ${{ github.ref == 'refs/heads/master' && 'wpenginesitename' || '[change-to-staging]' }}
      PROD_SITE_URL: ${{ github.ref == 'refs/heads/master' && 'https://wpenginesitename.mill3.dev/' || 'https://[change-to-staging].wpengine.com/' }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      SITE_NAME: "wpenginesitename"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ${{ env.THEME_PATH }}package-lock.json
      - name: Copy env.production sample file to .env
        working-directory: ${{ env.THEME_PATH }}
        run: cp .env.production .env
      - name: Install dep
        working-directory: ${{ env.THEME_PATH }}
        run: npm ci
      - name: Webpack build command
        id: build
        working-directory: ${{ env.THEME_PATH }}
        run: npm run build
      - name: Deploy to WPEngine
        if: ${{ success() }}
        uses: wpengine/github-action-wpe-site-deploy@v3.1.1
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: ${{ env.WPENGINE_ENV_NAME }}
          PHP_LINT: FALSE
          FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
          CACHE_CLEAR: TRUE
          SRC_PATH: ${{ env.THEME_PATH }}
          REMOTE_PATH: ${{ env.THEME_PATH }}
      - name: Notify to Slack
        if: ${{ success() }}
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#notifications'
          config: .github/slack.yml


